### PR TITLE
Fixed issue #3. Format and minor syntax changes to New-NsxManager.

### PR DESCRIPTION
**Pull request by vScripter**
- Added a filter when selecting VMHost to only select a host that is reporting a `Connected` status. ( Issue #3 )
- Added logic to throw an error if there are no hosts available in the cluster (either there are none or they are all in maint. mode, etc.) ( Issue #3 )
- Added Begin/Process/End blocks for language consistency
- Expanded support for -Verbose
- Added curly braces `{}` to some of the output messages that expect values so that it's easy to decipher if there is an expected value but none returned during runtime
- Modified check for vCenter server to inspect the 'IsConnected' property; ran into some cases where the `$Global:DefaultViServer` variable is populated but connection is stale/timed-out
- Misc spacing/formatting to improve readability a little bit

*My editor trims white space off the end of lines which results in nearly every line being a diff; I did my best to only stage the chunks relevant to my changes/additions*

Resolves: #3

### CODE REVIEW

**Comment by nmbradford** [comment]
Gah - the CRLF mangling your editor is doing is yuk! :(  Any chance you are using Atom? I had the same issue with @pandom - and we found Atom wasn't honoring the original formatting of the file.  There is a plugin to check and configure it dynamically - any chance you could take a look, fix and update PR? :)

**Comment by vScripter** [comment]
No prob; I can fix and resubmit. What's the default line ending you're using? I'm using VS Code, but I set all my files to LF; I also have enable trim white space and normalize line endings on save, so if there is a CR at the end of the line, it trims it off; I'll try disabling that and see if it helps.

**Comment by nmbradford** [comment]
Actually - looks like this is how I should be handling it 
https://help.github.com/articles/dealing-with-line-endings/#platform-all 
Will review and apply if appropriate...

**Comment by nmbradford** [comment]
@vScripter I have explicitly configured CRLF line endings in .gitattributes for repo now.  Want to pull, and try recommitting your changes again and see if Git magically works it out for you?

**Comment by vScripter** [comment]
Yep; I'll rebase my branch and see if it fixes it; if not, I'll just copy my changes out, clean and paste it back in.

**Comment by vScripter** [comment]
@nmbradford Yikes; I rebased and my local repo attached to this branch was rather upset, Lol. I'll have to sit down later and work through the merge conflicts; I should be able to get it all squared away without having to start a brand new PR.

**Comment by vScripter** [comment]
Closing this PR; it was easier for me to create a new branch and start new.

Ref PR #20

**Pull request closed without merging**
