### PR TITLE
Added New-NSXSecurityPolicy Functions

### PR DESCRIPTION
**Pull request by Virtualizestuff**
Added New-NSXSecurityPolicy and New-NsxSecurityPolicyFirewallRuleSpec Functions. :)

### CODE REVIEW

**Comment by Virtualizestuff** [comment]
Hey Nick,

I redid the SSO credential code as the previous code only allowed SSO credentials with Enterprise privilege to perform API request due. I added additional checks that allow the admin account to perform initial connection (Connect-NSXServer) then uses the SSO credentials for any other requests provided that account has permission. I have the new version completed just trying to figure out how to upload a new branch with those changes.

**Comment by nmbradford** [comment]
there isnt a lot of point in needing admin for connect, and then sso for other command is there?  Do I understand your approach correctly?  I have just SSO credentials working in Connect-NsxServer - which simply ignores failure to get version information from the appliance-management api (which is what requires admin)

**Comment by Virtualizestuff** [comment]
The initial connection to NSX Manager (Connect-NSXServer) populates the $connection variable with information obtained by the /api/2.0/services/vcconfig and a test on /api/1.0/appliance-management/global/info. 

The vcconfig requires an account with Enterprise_admin/Super_User to obtain the information. If I use another account i.e. security_admin it will not get this information and Connect-NSXServer will error out. If you like we can setup a webex if further explanation is needed.

**Comment by nmbradford** [comment]
ah - ok - thats clearer, i hadnt tested with any sso account less than ent_admin - it sounds like you are ahead of me.  Lets have a chat next week?(in the US this week on training and flying back tomorrow)

**Comment by Virtualizestuff** [comment]
Absolutely send me a webex invite for a time that's convenient for you.

**Comment by Virtualizestuff** [comment]
Here you go Nick I added a new pull request for SSO credentials. 
https://github.com/vmware/powernsx/pull/160

**Comment by nmbradford** [comment]
Jenkins run tests please.

**Comment by nmbradford** [comment]
Jenkins run tests please.

**Comment by nmbradford** [comment]
Jenkins run tests please.

**Comment by Virtualizestuff** [comment]
closing this pull request will be opening new one with updated code.

**Pull request closed without merging**
