### PR TITLE
Fixed issue #3. Format and minor syntax changes to New-NsxManager.

### PR DESCRIPTION
**Pull request by vScripter**
- Added a filter when selecting VMHost to only select a host that is reporting a `Connected` status. ( Issue #3 )
- Added logic to throw an error if there are no hosts available in the cluster (either there are none or they are all in maint. mode, etc.) ( Issue #3 )
- Added Begin/Process/End blocks for language consistency
- Expanded support for -Verbose
- Added curly braces `{}` to some of the output messages that expect values so that it's easy to decipher if there is an expected value but none returned during runtime
- Modified check for vCenter server to inspect the 'IsConnected' property; ran into some cases where the `$Global:DefaultViServer` variable is populated but connection is stale/timed-out
- Misc spacing/formatting to improve readability a little bit

*Line endings should be normalized; it was easier to fix on a new branch vs. trying to clean up [PR 14](https://github.com/vmware/powernsx/pull/14) 

Resolves: #3

### CODE REVIEW

**Comment by nmbradford** [comment]
Thanks Kevin. The substantive changes are great!  Most comments/questions I have are style related.

1) Change to 'style' in terms of throw output to [$($MyInvocation.MyCommand.Name)][ERROR] .....  I like this, but for now its inconsistent with the rest of PowerNSX.  Can we remove from this commit and if you feel up to the task, change output across the whole module in a separate commit / PR?

2)  Like wise with {} output in Write-progress, but Im less in favour of the actual change.  Personally - I prefer the approach _moving to folder : $foldername_. Or if its empty, test for it and skip the execution altogether (preferable)
 
3) Like wise change from out-null to cast to [void].  @pandom has been bugging me about this, and Im in favour (though there are other things Im more in favour of! :) ), but if we are going to make a style change, lets make it in a separate commit and apply it consistently throughout the whole module.
 
4) Change from 3826 :      If ( -not (test-path variable:global:defaultVIServer )) { 
 to 3872: ' If ( -not ($Global:defaultVIServer).IsConnected ) {'  will cause an unhandled exception if $DefaultVIServer doesn't exist (the module runs in strict mode, so referencing a var that doesn't exist will throw).  Would be better to retain the existing test-path and then put the if .isconnected within it.

5) Why the Begin/Process/End change?  This is really only valuable when the function accepts pipeline input unless I'm missing something.  I'm sure I'm not 100% consistent, but for the most part that should be the case throughout the module?

**Comment by vScripter** [comment]
### Responding in-line

1. *Change to 'style' in terms of throw output to [$($MyInvocation.MyCommand.Name)][ERROR] ..... I like this, but for now its inconsistent with the rest of PowerNSX. Can we remove from this commit and if you feel up to the task, change output across the whole module in a separate commit / PR?*. 

    **Yea, I thought the same thing, as far as consistency; I'm glad you brought it up. I can work on normalizing output streams across the entire module if we agree to the format standard/s. I typically do something to the effect of:**
    ```powershell
    # Warning 
    Write-Warning -Message "[$($MyInvocation.MyCommand.Name)][WARNING] $messageText"
    # Error
    throw "[$($MyInvocation.MyCommand.Name)][ERROR] $messageText"
    # Verbose
    Write-Verbose -Message "[$($MyInvocation.MyCommand.Name)] $messageText"
    ```

2. *Like wise with {} output in Write-progress, but Im less in favour of the actual change. Personally - I prefer the approach moving to folder : $foldername. Or if its empty, test for it and skip the execution altogether (preferable)*

    **I'm somewhat indifferent to this and admittedly it got added due to a mixture of muscle memory and template snippets. The basis of the idea is that in message that hits the screen or a log (particularly logs) has `{}` around a value that is populated from a variable so that if you are parsing/expecting a value to exist in a log, you can pretty quickly find entires that did return data from a variable. I actually have a `Write-Log` function that I use in my modules that allows you to supply a single message and depending on which 'mode' you use, it will handle where to put that message (CLI, Log, Debug, all, etc.). That being said, I can cut the whole change out.**

3. *Like wise change from out-null to cast to [void]. @pandom has been bugging me about this, and Im in favour (though there are other things Im more in favour of! :) ), but if we are going to make a style change, lets make it in a separate commit and apply it consistently throughout the whole module.*

    **Yep, I'm find with that; I'd rather change it all vs. only some and then everything ends up in a partially consistent state.**

4. *Change from 3826 : If ( -not (test-path variable:global:defaultVIServer )) { 
to 3872: ' If ( -not ($Global:defaultVIServer).IsConnected ) {' will cause an unhandled exception if $DefaultVIServer doesn't exist (the module runs in strict mode, so referencing a var that doesn't exist will throw). Would be better to retain the existing test-path and then put the if .isconnected within it.*

    **This is true; I forgot you are calling that in the module (Set-StrictMode). The following passed the smoke test, for me; this similar to what you were thinking? (disclaimer: code is raw; killed 4 kittens using `Write-Host`).**


```powershell
function xViServerTest {

    Set-StrictMode -Version Latest

    $variablePathTest = Test-Path Variable:Global:defaultVIServer

    If ( -not ($variablePathTest -eq $true) ) {

        Write-Host -fore red -Object "Unable to deploy NSX Manager OVA without a valid PowerCLI connection.`
        Use Connect-VIServer or Connect-NsxServer to extablish a PowerCLI connection and try again."
        
    } elseif ($variablePathTest -eq $true) {

        Write-Host 'Testing connected status' -fore yellow
        
        if (($Global:defaultViServer).IsConnected -eq $true) {

            Write-Host "Currently connected to VI Server: $Global:defaultViServer" -fore green

        } else {

            Write-Host "VI Server present, but not connected. You must be connected to a VI Server to continue." -fore red

        } # end if/else

    } # end if/elseif

} # end function xViServerTest
```

5. *Why the Begin/Process/End change? This is really only valuable when the function accepts pipeline input unless I'm missing something. I'm sure I'm not 100% consistent, but for the most part that should be the case throughout the module?*

    **You are correct that accepting pipeline input is where it's critical, particularly specifying a `process {}` block. That being said, I typically try to keep the general structure in place for a couple reasons, neither of which are technical requirements:
    1. Try to keep all 'Advanced Function' syntax looking the same way, even if no parameters accept pipeline input in the current version. Personally, it's more of a BDD thinking excercise around future support and how the syntax should be layed out, devoid of parameter/parameter attributes/accepting pipeline input/etc., on Day 0.
    2. OCD - I use it to help logically break up code within a function. Below is a snippet of what my function scaffold generally looks like**

    **Certainly not a hard requirement. If you would rather address later/not at all, perfectly fine by me.**

```powershell
function Show-FunctionSyntaxExample {

<#
.SYNOPSIS
    PS Function Scaffold
#>

    [OutPutType()]
    [CmdLetBinding()]
    param()

    BEGIN {

        # code to setup the function/report processing started

    } # end BEGIN block

    PROCESS {

        # code to perform the thing

    } # end PROCESS block

    END {

        # code to clean things up/report processing complete

    } # end END block

} # end function Show-FunctionSyntaxExample
```


**TODO**
- [ ] Collectively agree on output syntax outlined in `#1`
- [ ] I'll pull the change in `#1` out of this PR, open a new issue and then work on normalizing the entire module, based on an agreed format.
- [ ] I'll take out the `{}` talked about in `#2`
- [ ] Review update to handling VIServer connection; I will fix as part of this PR
- [ ] Decide if you want me to tear down the `begin{} process{} end{}` formatting from this PR

**Comment by nmbradford** [comment]
```#1 ```
- Fine with universal addition of $($MyInvocation.MyCommand.Name) to all ouput (warning and error) I usually use this (and a quick search shows it in some powernsx function output :) ).  
- On including ERROR/WARNING - this is clearly useful for log output, but for write-warning/write-verbose, this is redundant because both of them include these strings in the output anyway! Happy to leave this out?

If you are happy to standardise on just including $($MyInvocation.MyCommand.Name) in all output and leave it at that, then lets consider it agreed and make a separate PR for wholesale fix to all output to include.

```#2```  Cool!

```#3``` Cool!

```#4``` Perfect - although Id just include test-path within the if statement - the approach is fine.

```#5``` (that somehow became ```#1``` :) ) Consider me convinced for style change, keep it in your existing PR (I'm already using it a little inconsistently elsewhere) and raise a separate issue to update the rest of the module separately.

**Comment by vScripter** [comment]
Okay; I think I got everything we talked about in the most recent two commits. 🍻

**Comment by nmbradford** [comment]
Agreed!  Thanks @vScripter !

**Pull request merged**
