### PR TITLE
Service Group support in Security Policy Firewall Rules

### PR DESCRIPTION
**Pull request by dcoghlan**

### CODE REVIEW

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by nmbradford** [comment]
Jenkins test this please

**Comment by nmbradford** [comment]
jenkins test this please

**Comment by nmbradford** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by paulowen** [comment]
Hi @dcoghlan, I don't think the change in this PR is complete to achieve the functionality.

I was about to create a new PR before I saw this one. I have the intended functionality working with the attached diff below. An applicationGroup XML element is required for a service group within the applications parent element. The code currently only caters for an application XML element for service objects.

[pr442.txt](https://github.com/vmware/powernsx/files/1611127/pr442.txt)

I hope this helps.

**Comment by dcoghlan** [comment]
Hi @paulowen 

Thanks for the heads up. Well done on catching that. I will update my PR with the required changes and also associated tests and hopefully get this merged shortly once we get our test harnesses all completing successfully again.

DC

**Pull request merged**
