### PR TITLE
Enhance Load Balancer Tests

### PR DESCRIPTION
**Pull request by alagoutte**
Enhance LB Test 
* Add Remove LB AppProfile
* Add tests for monitor (Add / Remove)
* More test for Set-NSXLoadBalancer
...

### CODE REVIEW

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
@alagoutte are you able to rebase this PR and then I will kick off the tests

**Comment by alagoutte** [comment]
Updated :)

**Comment by dcoghlan** [comment]
jenkins test this please

**Pull request merged**
