### PR TITLE
Updated Get-NsxTransportZone examples

### PR DESCRIPTION
**Pull request by dcoghlan**
Added additional examples

### CODE REVIEW

**Comment by pandom** [comment]
Test this please

**Comment by dcoghlan** [comment]
test this please

**Comment by dcoghlan** [comment]
test this please

**Comment by pandom** [comment]
test this please

**Comment by pandom** [comment]
retest this please

**Comment by nmbradford** [comment]
restest this please

**Comment by nmbradford** [comment]
this guys is pretty dodgy... needs a lot of testing...

**Comment by nmbradford** [comment]
test this please

**Pull request merged**
