### PR TITLE
Master

### PR DESCRIPTION
**Pull request by rhancock8**
Modified New-NSXFirewallRule service validation function to accept servicegroups in addition to just services.

Removed 3 duplicate function declarations - Validate-Service, Validate-ServiceGroup and Validate-ServiceOrServiceGroups

### CODE REVIEW

**Comment by nmbradford** [comment]
Hey @rhancock8 - thanks for the PR.  Can we separate unrelated changes into different PRs?  The fix service-group for new-nsxfirewallrule I just fixed last night without even realising youd hit and already done that (bad me for sitting on PR - sorry, but not required now!) and the removing duplicates are an obvious quick merge, but I want to review the set-nsxlogicalrouter function separately.  We need to create some tests around it.

**Comment by rhancock8** [comment]
Hi @nmbradford , I certainly can separate stuff out... but may need some assistance on how to do that :(
I can re baseline my branch against any changes.. would that get rid of the servicegroup one (if you've already fixed it )?

**Comment by nmbradford** [comment]
Jenkins run tests please.

**Comment by nmbradford** [comment]
Jenkins run tests please.

**Comment by nmbradford** [comment]
Jenkins run tests please.

**Comment by dcoghlan** [comment]
Closing this due to inactivity. Please reopen if still required.

**Pull request closed without merging**
