### PR TITLE
Get-NsxApplicableMember universal flag

### LINKED ISSUE #276: Get-NsxApplicableMember universal enhancements
cmdlet by default only returns object on globalroot-0.

Specifying -scopeid universalroot-0 will return universal objects, however the behaviour should be brought into line with the other universal changes that have been made recently.

### PR DESCRIPTION
**Pull request by dcoghlan**
- Changes to allow universal applicable members to be returned.
- Changes to force validation of scopeid
Fixes #276

### CODE REVIEW

**Comment by nmbradford** [comment]
lgtm - did you test?

**Comment by dcoghlan** [comment]
No pester tests unfortunately. Manual tests on core and windows both worked ok.
Do you want me to write some tests for this one before merging?

**Comment by nmbradford** [comment]
yeah - if you dont mind :)

**Comment by dcoghlan** [comment]
Wrote some tests as discussed.
SecurityGroups and ServiceGroups tests pass on both Windows and Core.

**Comment by dcoghlan** [comment]
Fixes #276

**Pull request merged**
