### PR TITLE
Fixed New-NsxLoadBalancerPool

### PR DESCRIPTION
**Pull request by neoxinth**
#434 Fixes  New-NsxLoadBalancerPool - fixed building right XML-file, right path to the API and change to POST from PUT in invoke-nsxwebrequest

### CODE REVIEW

**Comment by jendm** [comment]
I tested this and got this to work.  Thank you.  We were having issues with the version in master and this saved us a lot of time.

However I had to change 1 line in order for it to work.
I changed this -- $body = $_LoadBalancer.OuterXml
To this -- $body = $xmlPool.OuterXml

**Comment by Nick-Andreev** [comment]
Hey, guys. Could you let me know why this hasn't been merged yet? We are having the same issue. Happy to write a test for you, if that's what's blocking it. @dcoghlan @alagoutte

**Comment by alagoutte** [comment]
Hi Nick,

Because missing test..

Do you known how to reproduce this issue ?

**Comment by Nick-Andreev** [comment]
Yes, I'll add a load balancer test.

**Comment by dcoghlan** [comment]
Addressed as part of #611

**Pull request closed without merging**
