### PR TITLE
Add Get-NsxIPsecStats

### LINKED ISSUE #353: Need Script to display the NSX IP sec VPN Status and Statistics
HI All, 

Need help in getting the NSX IP sec Statistics using script.  
ip sec vpn statitics

I am able to get the status up to VPN  using this command but not able to get the IPsec VPN Statistics as per the attached screen shot.  
$nsxvpnedge = Get-NsxEdge | where {$_.Name -match ("vpn")}
$nsxvpnedge.features.ipsec.sites.site

Please help me in getting this.

Thank you 
Nandeesh M

### PR DESCRIPTION
**Pull request by alagoutte**
PS /home/alagoutte/powernsx> (Get-NsxEdge edge01 | Get-NsxIPsecStats).siteStatistics.ikeStatus

channelStatus            : down
channelState             : Unknown
lastInformationalMessage :
localIpAddress           : 10.200.11.143
peerId                   : 2.2.2.2
peerIpAddress            : 2.2.2.2
localSubnets             : localSubnets
peerSubnets              : peerSubnets

PS /home/alagoutte/powernsx> (Get-NsxEdge edge01 | Get-NsxIPsecStats).siteStatistics.tunnelStats

tunnelStatus lastInformationalMessage localSubnet     peerSubnet
------------ ------------------------ -----------     ----------
down                                  192.168.44.0/24 192.168.23.0/24

Fix #353

### CODE REVIEW

**Comment by nmbradford** [comment]
here's a perfect chance for some tests! :)  nice and simple...

**Comment by alagoutte** [comment]
>here's a perfect chance for some tests! :) nice and simple...

I need to write a test ?

**Comment by nmbradford** [comment]
Any new functionality *should* have tests that validate its function.  That way when someone in the future breaks your code in some way, your test fails, and someones feature isn't merged until they fix it.  Now I know you are going to raise the fact that there are merges that have occurred without tests, and all I can do to justify myself is to point out the 30k lines odd of code that I'm still working through adding them for (and have already got a fair way).  I'm really trying to ask for community contribs to include tests as a minimum.

**Comment by alagoutte** [comment]
Ok, i understood but actually there is no really other function for IPsec and it only get stats... i will look for write a small test...

**Comment by nmbradford** [comment]
exactly - nice and easy! :)  Just trying to ease you into the concept ;)

**Comment by alagoutte** [comment]
Add a IPsec tests suite...

**Comment by alagoutte** [comment]
and rebase... :-)

**Comment by alagoutte** [comment]
Fix rebase issue

Can you check ?

**Comment by alagoutte** [comment]
@nmbradford, rebase my patch, it is possible to look ?

**Comment by alagoutte** [comment]
rerebase my patch, someone for look ?

**Comment by sebastiangrugel** [comment]
If this command is available now ? in current release ? i need use this command during before upgrade NSX edge :)

**Comment by alagoutte** [comment]
Hi Sebastian

No it is not yet available :(

you can clone my repo (and branch) for use it...

@dcoghlan can you look ? (and relaunch test ?)

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
> jenkins test this please

Tests failed due to datastore issue on one of the hosts, however, your tests passed.

**Pull request merged**
