### PR TITLE
New-NsxIpSet Universal Functionality

### PR DESCRIPTION
**Pull request by dcoghlan**
Made some simple modifications to the New-NsxIpSet to allow creation under the universalroot-0 scope for issue #151

### CODE REVIEW

**Comment by nmbradford** [comment]
Awesome - did you exec the existing ipset test suite after your changes?  Assume it works - just making sure...

**Comment by dcoghlan** [comment]
yeah let me see what I can come up with. i've noticed that there also doesn't seem to be any tests for IP Sets with a scope of an edge.

**Comment by nmbradford** [comment]
yup - just add a place holder test - or feel free to write one :)

**Comment by nmbradford** [comment]
awesome - lgtm - thanks!

**Pull request merged**
