### PR TITLE
Fix not drawing connections for universal logical switches

### PR DESCRIPTION
**Pull request by smitmartijn**
Also look at universalwire's for connections (fixes not drawing connections for universal logical switches)

### CODE REVIEW

**Comment by alagoutte** [comment]
Hi Martijn,

Push also on nsx-powerops repo ? https://github.com/vmware/nsx-powerops/tree/master/DiagramNSX 

No sure, where it is the official/upstream repo for this tools...

**Comment by smitmartijn** [comment]
Hey Alexis,

That might be a good idea, thanks. I know it originated in PowerNSX and for some reason they put a different copy there. Maybe there's a better chance of getting merged there, considering the inactivity here.

**Comment by alagoutte** [comment]
Yes, i have the same issue about merge some PR...

**Comment by nmbradford** [comment]
Hi guys - sorry for the inactivity - @smitmartijn I had a similar request internally last week that I need to attend to, so Ill try to take a look at this shortly.  Thanks for the PR.

**Comment by dcoghlan** [comment]
Hey @smitmartijn, sorry but I didn't see this PR until just now. Your fix was correct, however this is now fixed in #544.

**Pull request closed without merging**
