### PR TITLE
Permitting blank descriptions for new grp objects

### PR DESCRIPTION
**Pull request by tlindsay42**
Removed the ValidateNotNullOrEmpty test from the description parameter 
for the following cmdlets
- New-NsxSecurityGroup
- New-NsxIpSet
- New-NsxMacSet
- New-NsxService
- New-NsxServiceGroup

### CODE REVIEW

**Comment by tlindsay42** [comment]
Ready for review

**Comment by tlindsay42** [comment]
Forgot to mention the use case. I wrote a script for cloning the distributed firewall and the underlying objects, and would prefer not to have to test if the description exists and then call the new grouping object with the description field, and make the exact same request without the description if not. 

Example:
If ( $description.length -gt 0 ) {
  New-NsxGroupingObject -Description $description
}
Else { New-NsxGroupingObject }

I can use Invoke-NsxRestMethod as a workaround if this is undesirable for the cmdlets as the NSX Manager permits blank descriptions in new grouping object requests.

**Comment by nmbradford** [comment]
Interesting.  1) Would you be prepared to share the script you've written - sounds like this would be a great inclusion in the tools section (Understand if its IP that you need to keep closed though)
2)  I'm not sure there isn't a cleaner way to deal with it in your code, but on the surface, your request sounds reasonable, although validation minimums are something I prefer to keep to.  Would modifying your PR to be just validatenotnull() resolve your issue?

**Comment by tlindsay42** [comment]
Q1) Would you be prepared to share the script you've written - sounds like this would be a great inclusion in the tools section (Understand if its IP that you need to keep closed though)
A1) I would love to share, but unfortunately yes, I wrote that script for Armor.

Q2) I'm not sure there isn't a cleaner way to deal with it in your code, but on the surface, your request sounds reasonable, although validation minimums are something I prefer to keep to. Would modifying your PR to be just validatenotnull() resolve your issue?
A2) Agreed on the input validation minimums and that does resolve my issue.  The update is ready for your review.

**Comment by nmbradford** [comment]
Thanks @tlindsay42

**Pull request merged**
