### PR TITLE
Set-NsxLogicalSwitch: Fix using Multi connection

### LINKED ISSUE #640: Set-NSXLogicalSwitch -Connection argument bug
Hi guys,

I've been working on an NSX script recently, combining some PowerNSX outlets (Logical Switch related) with native NSX API calls (DFW related). However, upon testing, I noticed that one of the outlets is not working as expected (or as I am expecting it to work :)).

Finding: It seems that the Set-NSXLogicalSwitch does not handle the "-Connection" argument properly. I specify it as follows:

$LS | Set-NSXLogicalSwitch -Name "VVscriptrename" -Connection $NSXConn

Error: See error.txt attached. What it basically indicates is that the $NSXConn is not a valid PowerNSX connection object (it doesn't see Credential/uriprefix/protocol properties).

I know for a fact that my $NSXConn is a valid connection object however, as it works with other PowerNSX outlets. E.g., this works fine (with $defaultNSXConnection being empty, just to make sure it isn't falling back) :

$NSXConn = Connect-NSXServer -vCenterServer $vcFRA -Credential $cred -DefaultConnection:$false -VIDefaultConnection:$false -ErrorAction Stop

$LS = Get-NSXLogicalSwitch -Transportzone $nsxLocalTZ -Connection $NSXConn -Name "VVscripttest" -ErrorAction Stop

I've added the "-Defaultconnection" and "-VIDefaultConnection" arguments later, for testing purposes, but both with and without these arguments, the Set-NSXLogicalSwitch fails.

Workaround: as I'm using try/catch blocks, I will always enter the catch block and my script will terminate. A workaround is to have a default NSX connection set ($defaultNSXConnection), so that it will fallback to that (it works, I tested it), but in my case this is not workable, as my script is connecting to multiple NSX instances and I need to perform actions on specific NSX instances based on certain logic.
I've stored these instances as objects in an array to loop over them to do operations on multiple NSX instances (based on specific logic).

Can you guys check it out?

Note: When reproducing, please make sure $defaultNSXConnection is empty, after connecting to your NSX instances and before u run the Set-NSXLogicalSwitch command with the -Connection argument.

Thanks and Regards,

Viresh
[error.txt](https://github.com/vmware/powernsx/files/6028759/error.txt)

### PR DESCRIPTION
**Pull request by alagoutte**
Fix #640

### CODE REVIEW

**Comment by alagoutte** [comment]
hi @dcoghlan can you look for merge this quick fix ?

**Comment by dcoghlan** [comment]
> hi @dcoghlan can you look for merge this quick fix ?

Sorry, this change has 6,643 additions and 6,586 deletions. First I need to be able to see the exact changes made, and second, I need some tests to verify that the changes work and don't break backwards compatibility.

**Comment by alagoutte** [comment]
> 
> 
> > hi @dcoghlan can you look for merge this quick fix ?
> 
> Sorry, this change has 6,643 additions and 6,586 deletions. First I need to be able to see the exact changes made, and second, I need some tests to verify that the changes work and don't break backwards compatibility.

Oups fixed this issue (it think my editor change the indent/encoding)

**Comment by alagoutte** [comment]
can you look ?

**Pull request merged**
