### PR TITLE
Add Set-NsxLogicalSwitch

### PR DESCRIPTION
**Pull request by alagoutte**
to configure a Logical Switch (Name / Description) with test !

### CODE REVIEW

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by alagoutte** [comment]
Hi Dale,

Thanks for merging patchs about the CI fail, it is a false positive or there is a error ?

**Comment by dcoghlan** [comment]
> Hi Dale,
> 
> Thanks for merging patchs about the CI fail, it is a false positive or there is a error ?

Just a testbed issue as the NSX Managers were not up and running. Have resolved that now, so will kick off the tests again.

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
jenkins test this please

**Pull request merged**
