### PR TITLE
Updates to Tests to run on Core

### PR DESCRIPTION
**Pull request by dcoghlan**
Set Required Modules correctly.

### CODE REVIEW

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by nmbradford** [comment]
jenkins test this please

**Comment by nmbradford** [comment]
jenkins test this please

**Comment by nmbradford** [comment]
jenkins test this please

**Comment by alagoutte** [comment]
end of support of old PowerCLI(.vds) and powershell core beta ?

**Comment by alagoutte** [comment]
really need to have 3 different platform after ? because it is the same code now ?

**Comment by nmbradford** [comment]
Tests passing - still working through some kinks in the CI

**Pull request merged**
