### PR TITLE
Resolve Issue 566

### PR DESCRIPTION
**Pull request by NamedJason**
I added a line to allow remove-nsxSecurityGroupMember to properly detect excludeMember objects so that it can remove them.

I'm sorry if I'm doing this wrong, I'm a beginner with Git.  Please let me know if I need to do something differently.

### CODE REVIEW

**Comment by alagoutte** [comment]
Hi @NamedJason 

There is a issue when you change it is very big (you don't have change all indent ?)

**Comment by NamedJason** [comment]
Ok.  I used tabs for indents on my new lines, but then I saw that the rest of the file uses spaces, so that second edit was just me changing my new lines to use spaces, too.

________________________________

**Comment by alagoutte** [comment]
What editor do you have using ?

**Comment by NamedJason** [comment]
NPP - I usually use tabs, so I just did so here in my initial version.  When I uploaded it to github, it looked funky and that's when I realized that the rest of the file uses spaces instead, so I changed to try and follow the existing style.

________________________________

**Comment by dcoghlan** [comment]
fixed by #647

**Pull request closed without merging**
