### PR TITLE
Add missing test when disable sslvpn

### PR DESCRIPTION
**Pull request by alagoutte**
There is no test on the testsuite when disable sslvpn...

### CODE REVIEW

**Comment by nmbradford** [comment]
Thanks - It took me a few moments and git log review to work out that I just hadnt done that initially?  Any chance you want to add more SSL VPN tests to this PR before I merge?

**Comment by alagoutte** [comment]
No really plan to add more SSL VPN tests...
i found this typo when work on #412

**Comment by nmbradford** [comment]
ok - np - thanks @alagoutte - LGTM, Ill merge as soon as I get our testing backend functional again :|

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
jenkins test this please

**Pull request merged**
