### PR TITLE
Set-NsxLoadBalancer: use $variable.ToString().ToLower() instead of th…

### PR DESCRIPTION
**Pull request by alagoutte**
…e if/else

### CODE REVIEW

**Comment by nmbradford** [comment]
What issue is this addressing @alagoutte ?

**Comment by alagoutte** [comment]
No really a issue but only apply your recommendation from #439 (about boolean)

**Comment by nmbradford** [comment]
yeah - ok - its still functional though, I was just showing you a better way! (you will spend a lot of time not actually improving things if you go looking for changes like this in any code!).  Can I suggest you spend your time elsewhere?

**Comment by alagoutte** [comment]
it is only i have based my code on this... (and it is better the code have the same style...)

(and it is a quick fix...)

**Pull request closed without merging**
