### PR TITLE
FIPS Mode for ESG

### PR DESCRIPTION
**Pull request by dcoghlan**
- fixes #579 (Thanks to @rlakey for the original PR/Code)
- added ability to deploy ESG with FIPS enabled
- added cmdlets `Enable-NsxEdgeFips` and `Disable-NsxEdgeFips`
- many misc linter/formatting updates for the module and edge tests files

### CODE REVIEW

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by alagoutte** [comment]
Hi,

What do you have use for linter ? because all file change and it is not possible to display diff with github

**Comment by dcoghlan** [comment]
> Hi,
> 
> What do you have use for linter ? because all file change and it is not possible to display diff with github

VSCode.

to see the individual changes, they have been split into individual commits.

**Comment by alagoutte** [comment]
> 
> 
> > Hi,
> > What do you have use for linter ? because all file change and it is not possible to display diff with github
> 
> VSCode.
> 
> to see the individual changes, they have been split into individual commits.

Thanks, now it is merged, it is more easy to use git diff ;-)

can you make also the change to other file ? (Tests) and also move to Pester v5 ?

(What do you have use to have format PowerShell cmdlet ?)

**Pull request merged**
