### PR TITLE
Edge: Update minimum Ha DeadTime limit

### PR DESCRIPTION
**Pull request by alagoutte**
it is now 3 secs (before 6secs)

Fix issue #513

### CODE REVIEW

**Comment by dcoghlan** [comment]
Hey @alagoutte, If you can write some tests for this, it looks like a fairly easy one to merge.

**Comment by alagoutte** [comment]
Hi Dane,

it is a small change...
What test do you want ?

**Comment by nmbradford** [comment]
Just a simple 'can I set it' and 'When I set it, does the returned object have it set as I asked' style tests.  Just the two is fine.

**Comment by alagoutte** [comment]
It is a quick fix...

and there is no test for the moment for HA... 
And need to create a new Edge (you don't modified a setting from a Edge...)

**Comment by alagoutte** [comment]
No found test with HA...

**Comment by nmbradford** [comment]
You will note I didn't claim there was.  Just create a single test for this _in the existing edge tests_.

**Comment by alagoutte** [comment]
Adding a HA Tests

Can you launch test suite ?

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
jenkins test this please

**Comment by dcoghlan** [comment]
Tests failed due to testing harness failures. Your changes passed successfully.

**Pull request merged**
